SalesforceCommerceCloud/commerce-sdk

- packages/generator/templates/ClientInstance.ts.hbs
We expose the ClientConfig type a the root namespace of the SDK.  It is confusing to then export it at each client level as well. This just removed that redundant export as it shouldn't be needed.
> Removed ClientConfig

- packages/generator/templates/helpers.ts.hbs
1. Added back the previous version of getAuthToken function and marked as deprecated
2. Renamed the current version of getAuthToken function to getShopperAuthToken 
3. Simplified the input params of getShopperAuthToken
> auth helper changes

- packages/generator/src/parser.ts
- packages/generator/src/renderer.ts
- packages/generator/templates/ClientInstance.ts.hbs
- packages/generator/test/parser.test.ts
This change addresses the TODO comment that was added with api re-org story. 
Got rid of the code to create an array with single api model while rendering the templates
> Remove unnecessary arrays used for API model while rendering the templates

- packages/core/src/base/resource.ts
- packages/generator/src/templateHelpers.ts
- packages/generator/templates/helpers.ts.hbs
- packages/generator/templates/operations.ts.hbs
- packages/generator/test/template-helpers.test.ts
- packages/generator/test_integration/site_integration.test.ts
Resolves the return type ambiguity by overloading functions. Each function is overloaded by two functions. One returns the DTO when no value for rawResponse is provided. The other returns the DTO or Response object based on the value of rawResponse.
rawResponse is now its own param instead of a field on options object which it was before.
Implementing this solution increased the size of our SDK by ~75KB (Total unpacked SDK size before the change was 1.6MB). I also added extra tsdocs which further increased the size by ~130KB.
> Add two overload functions per function for Response and DTO return types

- packages/generator/src/renderer.ts
- packages/generator/src/templateHelpers.ts
- packages/generator/templates/dtoPartial.ts.hbs
- packages/generator/test/template-helpers.test.ts
Code to get data types is refactored to 
- use amf classes instead of any
- cleaned and  organized
- fixed unit tests
- removed unused functions related to data types
- compared the rendered files with my changes - no diffs founds except the below one which is actually a fix
```
export type QueryT = {
boolQuery?: {
must?: Array<any>;
mustNot?: Array<any>;
should?: Array<any>;
}& { [key: string]: any }
;
filteredQuery?: {
filter: any;
query: any;
}& { [key: string]: any }
;
........
```
is now rendered as
```
export type QueryT = {
boolQuery?: BoolQueryT;
filteredQuery?: FilteredQueryT;
matchAllQuery?: MatchAllQueryT;
nestedQuery?: NestedQueryT;
termQuery?: TermQueryT;
textQuery?: TextQueryT;
}& { [key: string]: any }
```
> Refactor code to get property data types in dtos

- packages/generator/src/renderer.ts
- packages/generator/src/templateHelpers.ts
- packages/generator/templates/operations.ts.hbs
- packages/generator/test/template-helpers.test.ts
Sample of rendered code with parameter ttpes
```
productSearch(
options?: {
parameters?: {
organizationId?: string
siteId?: string
q?: string
refine?: Array<string>
sort?: string
currency?: string
locale?: string
offset?: number
limit?: number
},
headers?: { [key: string]: string }
}
): Promise<ProductSearchResultT>;
```
> Render data types of parameters for endpoint operations

- packages/core/src/base/staticClient.ts
- packages/generator/README.md
This already works and has test coverage. Only doc coverage is required.
> Br/disable cache.w 7007712

- packages/generator/src/renderer.ts
- packages/generator/src/templateHelpers.ts
- packages/generator/templates/operations.ts.hbs
- packages/generator/test/template-helpers.test.ts
- packages/generator/test_integration/site-integration.test.ts
Sample rendered code
```typescript
promotionsSearch(
options: {
parameters?: {
organizationId?: string
siteId?: string
},
headers?: { [key: string]: string },
body: SearchRequestT
}
): Promise<PromotionSearchResultT>;
addItemToBasket<T extends boolean>(
options: {
parameters?: {
organizationId?: string
basketId: string
siteId?: string
},
headers?: { [key: string]: string }, 
body: Array<ProductItemT>
},
rawResponse?: T
): Promise<T extends true ? Response : BasketT>;
```
> Render data type for request body

- packages/core/test/static-client-caching-eviction.test.ts
New unit tests using cache manager to test cache eviction and updates
> Eviction tests using cache manager

- packages/generator/APICLIENTS.md
- packages/generator/src/renderer.ts
- packages/generator/src/templateHelpers.ts
- packages/generator/templates/apiclients.md.hbs
- packages/generator/test/renderer.test.ts
- packages/generator/test/template-helpers.test.ts
- Modified renderer to expose necessary information. Should also make adding generated examples easier in the future.
- Updated [APICLIENTS.md](https://github.com/SalesforceCommerceCloud/commerce-sdk/blob/wjh/update-usage-docs.W-7263996/packages/generator/APICLIENTS.md).
- Added test for `renderOperationList` to meet coverage threshold.
> Add example client instantiation to APICLIENTS.md

- .circleci/config.yml
It should fix the issue where there is inconsistency in package.json and package-lock.json and the build still passes.
We should be able to close `W-7424350: Build should fail if git status is not clean`
Here's how npm ci is different from npm install:
* The project must have an existing package-lock.json or npm-shrinkwrap.json.
* If dependencies in the package lock do not match those in package.json, npm ci will exit with an error, instead of updating the package lock.
* npm ci can only install entire projects at a time: individual dependencies cannot be added with this command.
* If a node_modules is already present, it will be automatically removed before npm ci begins its install.
* It will never write to package.json or any of the package-locks: installs are essentially frozen.
> Replace npm install with npm ci in circle ci config

- .circleci/config.yml
Dry run of npm publish with these settings worked as expected - https://app.circleci.com/pipelines/github/SalesforceCommerceCloud/commerce-sdk/1282/workflows/05fe13d5-f2d2-433b-8183-356f567bdf17/jobs/2115
> Use custom config for publish job

- packages/generator/.depcheckrc.yml
- packages/generator/package.json
Github pages uses jekyll, which ignores all files that start with _ . 
Typedoc is creating a couple of files (index and helpers) with leading (and trailing) underscores.
This adds a directive to typedoc to create a file named .nojekyll which tells github pages to not use jekyll.
> Adding support for .nojekyll

- packages/core/src/base/staticClient.ts
Changes
- Log fetch after assigning headers object
Acceptance Criteria
- Ensure in DEBUG log level, curl command includes headers
> Log fetch after assigning headers

- package-lock.json
- package.json
- packages/core/src/base/cacheManagerKeyv.ts
- packages/core/src/base/cacheManagerRedis.ts
Keyv expects specific types. This change updates the type definitions for the cache manager to use those types.
> Fix cache manager types

- src/renderer.ts
Due to method calls modifying the original objects..order mattered.  Needed to refactor to keep this in mind.  (We should update the methods to not modify original objects)
> Fix data type resolution for nested types

- docs/classes/customer.shopperlogin.html
- src/lib/config.ts
- src/lib/templateHelpers.ts
It's missing, which means that links in our documentation are broken.
Also changed the helper function to throw if an object ID is missing, so that we don't end up with broken links in the future.
> Add shopper login object ID

- apis/.metadata.json
- base.tsconfig.json
- src/generate.ts
- src/lib/templateHelpers.ts
- src/lib/utils.ts
- src/updateApis.ts
- templates/helpers.ts.hbs
- testIntegration/stagingApis/.metadata.json
This PR removes browser global from being used by the TypeScript compiler, and fixes broken code that incorrectly used those globals.
The `Response` used in [helpers.ts](https://github.com/SalesforceCommerceCloud/commerce-sdk/blob/86763b1255808a56e59f0a7d782943683223cab9/templates/helpers.ts.hbs#L11) is _supposed_ to refer to the `Response` exported by `minipass-fetch` (via `@commerce-apps/core`). It does not, because the class was not imported. This did not result in an error because TypeScript defaults to including types for browser globals. Changing the file to use the correct `Response` caused [`CustomerType`](https://github.com/SalesforceCommerceCloud/commerce-sdk/blob/86763b1255808a56e59f0a7d782943683223cab9/templates/helpers.ts.hbs#L11) to break. This is because there are no type …
> Remove browser globals and fix types

- package-lock.json
- package.json
- templates/operations.ts.hbs
- testIntegration/tests/requests.test.ts
Combined with https://github.com/SalesforceCommerceCloud/commerce-sdk-core/pull/86, will add support for endpoints that use `application/x-www-form-urlencoded`, i.e. SLAS.
(Build will fail until the upstream PR is merged and released.)
> Set Content-Type header for requests with bodies

- .npmrc
This PR is to ensure future node packages that are added pull from the npm registry instead of nexus due to CI pipeline issues where the CI is unable to connect to nexus
> W-11235782: Add .npmrc file to pull from npm registry instead of nexus

- .git2gus/config.json
Adding Git2Gus integration
Adding the following labels will create objects in Gus in the Commerce SDK product tag
type:dependency = Work Item
type:security = P2 Bug
type:bug = P3 Bug
type:community-contrib = Work Item
> chore: Add git2gus integration

- package-lock.json
- package.json
- testIntegration/tests/slasHelper.test.ts
This PR resolves issue https://github.com/SalesforceCommerceCloud/commerce-sdk/issues/368. This PR also contains an integration test that uses `nanoid` underneath the hood. The integration tests package the `commerce-sdk` to be used as node module, so the test pulls the slasHelpers from the `commerce-sdk` package and tests a basic guest login flow that uses `nanoid` through the slasHelpers.
To run the tests within the repository:
```bash
git checkout ju/fix_nanoid
cd testIntegration
npm run test:ci
```
> fix: use nanoid as regular dependency

- CHANGELOG.md
- README.md
- src/static/helpers/slas.test.ts
- src/static/helpers/slas.ts
Starting 7/31/2024, SLAS will start requiring the `channel_id` as a required argument when retrieving an access token with `grant_type: 'client_credentials` for security purposes. This PR updates the `loginGuestUserPrivate` SLAS helper function to require `channel_id`.
> Update SLAS helper to require channel_id

- CHANGELOG.md
- src/static/helpers/slas.test.ts
- src/static/helpers/slas.ts
- src/static/helpers/slasClient.ts
This PR allows custom parameters to be passed into `/authorize` endpoint via the `loginGuestUser` and `authorizeIDP` helpers  and `/login` via `loginRegisteredUserB2C` and `loginRegisteredUserB2Cprivate` helper. 
- Customer headers are not allowed and will be ignored via SLAS
Some Note on the authentication endpoints
- The /authorize endpoint does not call SCAPI / OCAPI customers/auth where the hooks take place.
- /login will have authentication hooks. See [here](https://developer.salesforce.com/docs/commerce/commerce-api/guide/hook-method-details.html)
> W-18089100 - allow custom params in helpers

- CHANGELOG.md
- src/static/helpers/slas.test.ts
- src/static/helpers/slas.ts
- templatesOas/apis.enum.mustache
This PR refactors the SDK in breaking ways:
- SLAS helpers accept a single options object argument 
- export only enum types and not a const variable
- Path parameters are URI encoded by default in a separate PR: https://github.com/SalesforceCommerceCloud/commerce-sdk-core/pull/119
> Feat: Refactor Node SDK (@W-18136408@)

- package-lock.json
- package.json
Fixes CI for: https://github.com/SalesforceCommerceCloud/commerce-sdk/pull/423
We had open API generator as a dependency but we don't use it directly, we have it through RAML toolkit so we can remove it, commerce-sdk-isomorphic does not have this dependency either
This PR also bumps up `commerce-sdk-core` version
> Fix snyk CI for feature OAS branch
