packages/generator/README.md
- Add salesforce to text for generated package
=> [jb/update-readme-2]

packages/generator/src/renderer.ts, packages/generator/src/templateHelpers.ts, packages/generator/templates/dtoPartial.ts.hbs, packages/generator/test/template-helpers.test.ts
Add regex for filtering regular expression properties
Removed supported additional properties regex.
Removed helper method to get only supported additional properties
=> Filter properties that are not regular expressions

package-lock.json, package.json, packages/generator/test_integration/site-integration.test.ts
A new npm package "conditional-type-checks" is added for type checks
=> Test to verify that paramter data types are rendered

packages/core/package.json, packages/exchange-connector/package.json, packages/generator/package.json, packages/generator/src/templateHelpers.ts
Also, extract  the common mocha options into a separate mocha property in all the packages
=> Add retries and increase timeout for integration tests

packages/core/src/base/cacheManagerKeyv.ts, packages/core/src/base/cacheManagerRedis.ts, packages/core/test/cache/delayedTests.tests.ts, packages/core/test/cache/etag.tests.ts, packages/core/test/cache/eviction.tests.ts, packages/core/test/cache/noCacheHeader.tests.ts, packages/core/test/cacheManagerKeyv.ttl.test.ts, packages/core/test/cacheManagerRedis.test.ts, packages/core/test_integration/staticClientCachingDriver.test.ts
1. Removed ttl method and replaced with cachable or not
2. used keyv method without 3rd optional ttl argument
=> Remove TTL and fix tests

packages/core/src/base/sdkLogger.ts, packages/core/src/index.ts, packages/core/test/sdkLogger.test.ts, packages/generator/README.md, packages/generator/docs/GENERATOR.md, packages/generator/package.json, packages/generator/src/logger.ts, packages/generator/src/renderer.ts, packages/generator/templates/index.ts.hbs, packages/generator/test/logger.test.ts
- Logger for generator
- Added unit test for both SDK logger and generator logger
- Updated README.md and GENERATOR.md
=> generator logger

packages/core/.snyk, packages/core/package-lock.json, packages/core/package.json, packages/generator/.snyk, packages/generator/package-lock.json, packages/generator/package.json
Snyk doesn't sign commits, so this is a signed version of the changes in #171, #172.
=> Redo Snyk PRs #171, #172

docs/vscode.md, packages/generator/docs/GENERATOR.md
* Info on `EXCHANGE_DOWNLOAD` is outdated and unneeded.
* The `.env` file with Anypoint credentials must be in a specific directory.
* Formatting.
=> Update generator docs

.depcheckrc.yml, package-lock.json, package.json
Follow-up to #261, restores another typedoc plugin that was accidentally removed. Also adds sort-package-json because it's helpful.
=> Restore nojekyll plugin and add sort package json

README.md, examples/01-guest-shopper-auth-token.ts, examples/02-registered-shopper-auth-token.ts, examples/03-refresh-auth-token.ts
Examples to retrieve 
1. authorization token for guest and registered customer
2. refresh token
=> Examples to retrieve auth token

package-lock.json, package.json, templates/ClientInstance.ts.hbs, templates/dtoPartial.ts.hbs, templates/operations.ts.hbs
Build is currently failing as it depends on https://github.com/SalesforceCommerceCloud/raml-toolkit/pull/128
=> Update dtoPartial template to handle array types

package.json
Changed the output format of the diff command to console 
```
APIs Changed
────────────
File: cdnapi-process-api.raml
─────
API Summary
───────────
Ignored Changes: 4
File: orders.raml
─────
No changes.
File: shopper-baskets.raml
─────
API Summary
───────────
Ignored Changes: 4
File: shopper-orders.raml
─────
No changes.
File: customers.raml
─────
API Summary
───────────
Ignored Changes: 4
File: shopper-customers.raml
─────
API Summary
───────────
Ignored Changes: 4
File: shopper-login.raml
─────
No changes.
File: slas-admin.raml
─────
No changes.
File: assignments.raml
─────
No changes.
File: campaigns.raml
─────
API Summary
───────────
Ignored Changes: 4
File: coupons.raml
─────
API Summary
───────────
Ignored Changes: 4
File: gift-certificates.raml
─────
No changes.
File: …
```
=> Change the diff output format to console

.eslintrc.json, .mocharc.json, .nycrc.json, package-lock.json, package.json, testIntegration/package.json, testIntegration/tests/setup.ts, testResources/setup.ts
- Add a setup file that contains mocha root hooks that stub console.log
- Update mocha to 8.2.1
- Extract mocha, nyc and eslint configs to their own separate files.
=> Stub console.log so that tests don't print to console

README.md
Added details about Errors to the README
=> Add error doc

package-lock.json, package.json
- Passed tests and integration tests
- Manually verified ShopperProducts.getProduct() API call
=> upgrade ram-toolkit & core to latest versions

src/lib/templateHelpers.ts
=> Moved comment into error message

package-lock.json, src/lib/config.ts, src/updateApis.ts
Add inventory and slas admin apis to the object map so that docs can be pulled from CCDC
Also, move cc api families list to config.ts
=> Add CCDC object ids of inventory and slas admin apis

CHANGELOG.md, docs/CHANGELOG.md, docs/index.html, docs/modules/cdn.html, docs/modules/checkout.html, docs/modules/customer.html, docs/modules/discovery.html, docs/modules/pricing.html, docs/modules/product.html, docs/modules/search.html
This PR is to trigger the CI pipeline to publish to NPM
=> Re-release v2.9.0

.github/workflows/publish.yml
The publish workflow is broken due to a snyk authentication issue: https://github.com/SalesforceCommerceCloud/commerce-sdk/actions/runs/6164359676/job/16729912619
This PR fixes that issue. The test workflow also faced this issue, but that fix was implemented in this PR: https://github.com/SalesforceCommerceCloud/commerce-sdk/pull/388/files
=> fix publish workflow @W-13761984@

.depcheckrc.yml, .github/workflows/test.yml, README.md, package-lock.json, package.json, src/static/helpers/slas.test.ts, src/static/helpers/slas.ts, src/static/helpers/slasClient.ts, src/test/parameters.test.ts, templates/ClientInstance.ts.hbs, templates/operations.ts.hbs
This PR adds support for custom query parameters as SCAPI now supports SCAPI hooks: https://developer.salesforce.com/docs/commerce/commerce-api/references/about-commerce-api/about.html#08302023
Query params that begin with `c_` are considered custom query parameters and are passed onto the underlying SCAPI call.
This PR also:
- adds filtering for invalid query parameters
- upgrades `typescript` and `ts-node` packages and fixes respective typescript errors due to upgrade
- updates CI to include node 18 and 20
To test this PR, you can build a local version of the `commerce-sdk` and use that as a package for manual testing:
1. `git clone -b feat/support-custom-params git@github.com:SalesforceCommerceCloud/commerce-sdk.git`
2. `cd commerce-sdk`
3. `npm install --legacy-peer-deps`
4. Add a …
=> Feat: Add support for custom query params @W-14391914@

.eslintrc.json, CHANGELOG.md, README.md, src/static/helperTemplates/index.ts.hbs, src/static/helpers/fetchHelper.test.ts, src/static/helpers/fetchHelpers.ts
This is the node SDK implementation for this Isomorphic SDK PR: https://github.com/SalesforceCommerceCloud/commerce-sdk-isomorphic/pull/189
Please see the attached PR for more context and details.
=> Feat: Add helper to encode special characters (@W-17577102@)
